Repository ivanspajic/SOVA, pull requests merged in 2019-12, with the labels that each got.

#148 Responsive design
  README.md
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/app.js
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.js
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
Labels: ready for review

#149 Updated to use Bootstrap
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
Labels: ready for review

#150 Responsive Bootstrap
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
Labels: ready for review

#152 Routing + Answers (responsive) page
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/app.js
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.js
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
  Subproject2/SOVA/wwwroot/js/main.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#156 Answers page with accepted and users
  Subproject2/Data Layer/QuestionRepository.cs
  Subproject2/SOVA/Controllers/QuestionsController.cs
  Subproject2/SOVA/Models/QuestionDto.cs
  Subproject2/SOVA/libman.json
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/knockout/LICENSE
  Subproject2/SOVA/wwwroot/knockout/README.md
  Subproject2/SOVA/wwwroot/knockout/build/output/knockout-latest.debug.js
  Subproject2/SOVA/wwwroot/knockout/build/output/knockout-latest.js
  Subproject2/SOVA/wwwroot/knockout/build/types/knockout.d.ts
  Subproject2/SOVA/wwwroot/knockout/package.json
  Subproject2/SOVA/wwwroot/lib/moment/min/moment-with-locales.js
Labels: ready for review

#159 Responsive answers page
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
Labels: ready for review

#160 Responsive Comments
  Subproject2/Data Layer/QuestionRepository.cs
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
Labels: ready for review

#161 Move navbar to its own component and authentication
  Subproject2/SOVA/Controllers/UsersController.cs
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/app.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/user-profile/user-profile.html
  Subproject2/SOVA/wwwroot/js/components/user-profile/user-profile.js
  Subproject2/SOVA/wwwroot/js/main.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
Labels: ready for review

#167 User sign up and authentication token in local storage
  Subproject2/SOVA/Controllers/AuthController.cs
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.js
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.html
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/signup-page/signup-page.html
  Subproject2/SOVA/wwwroot/js/components/signup-page/signup-page.js
  Subproject2/SOVA/wwwroot/js/components/user-profile/user-profile.html
  Subproject2/SOVA/wwwroot/js/components/user-profile/user-profile.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#163 Working on history.
  Subproject2/SOVA/wwwroot/js/main.js
  Subproject2/SOVA/wwwroot/js/services/history.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#171 Updated design and user can sign out
  Subproject2/1. SOVA/appsettings.dbConnectionString.json
  Subproject2/SOVA/Controllers/AuthController.cs
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.html
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/signup-page/signup-page.html
  Subproject2/SOVA/wwwroot/js/components/signup-page/signup-page.js
  Subproject2/SOVA/wwwroot/js/components/user-profile/user-profile.html
  Subproject2/SOVA/wwwroot/js/services/history.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#173 User sign up no password fix and improved UX
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.html
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/signup-page/signup-page.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#174 searching back to back fix
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#177 Small additions to the navbar.
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
Labels: work in progress

#181 Wordcloud
  Subproject2/Data Layer Abstractions/IQuestionRepository.cs
  Subproject2/Data Layer/Database Context/SOVAContext.cs
  Subproject2/Data Layer/QuestionRepository.cs
  Subproject2/Models/CloudElement.cs
  Subproject2/SOVA/Controllers/QuestionsController.cs
  Subproject2/SOVA/libman.json
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.html
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.js
  Subproject2/SOVA/wwwroot/js/main.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
  Subproject2/SOVA/wwwroot/lib/jqcloud2/dist/jqcloud.css
  Subproject2/SOVA/wwwroot/lib/jqcloud2/dist/jqcloud.js
  Subproject2/SOVA/wwwroot/lib/jqcloud2/dist/jqcloud.min.css
  Subproject2/SOVA/wwwroot/lib/jqcloud2/dist/jqcloud.min.js
Labels: ready for review

#188 Refresh stays on the same page
  Subproject2/SOVA/Controllers/MarkingsController.cs
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/app.js
  Subproject2/SOVA/wwwroot/js/components/individual-answer/individual-answer.js
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.js
  Subproject2/SOVA/wwwroot/js/components/login-page/login-page.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
  Subproject2/SOVA/wwwroot/js/components/signup-page/signup-page.js
  Subproject2/SOVA/wwwroot/js/components/tag-filter/tag-filter.js
  Subproject2/SOVA/wwwroot/js/services/dataService.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#190 Uplift to search results and tags filter page
  Subproject2/Data Layer/QuestionRepository.cs
  Subproject2/SOVA/wwwroot/assets/images/Filter icon.png
  Subproject2/SOVA/wwwroot/assets/images/No-results.gif
  Subproject2/SOVA/wwwroot/assets/images/home.png
  Subproject2/SOVA/wwwroot/assets/images/search.png
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.js
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.html
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.js
  Subproject2/SOVA/wwwroot/js/components/tag-filter/tag-filter.html
  Subproject2/SOVA/wwwroot/js/components/tag-filter/tag-filter.js
Labels: ready for review

#194 Responsiveness
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/assets/images/search for form.png
  Subproject2/SOVA/wwwroot/index.html
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.html
  Subproject2/SOVA/wwwroot/js/components/landing-page/landing-page.js
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.html
  Subproject2/SOVA/wwwroot/js/components/tag-filter/tag-filter.html
  Subproject2/SOVA/wwwroot/js/services/dataService.js
Labels: ready for review

#195 Responsive annotations and uplifting the design
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
Labels: ready for review

#199 User Annotations page
  Subproject2/Data Layer Abstractions/IAnnotationRepository.cs
  Subproject2/Data Layer/AnnotationRepository.cs
  Subproject2/Data Layer/Database Context/SOVAContext.cs
  Subproject2/Models/Annotation.cs
  Subproject2/SOVA/Controllers/AnnotationsController.cs
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/assets/images/annotations-icon.png
  Subproject2/SOVA/wwwroot/assets/images/bookmark-icon.png
  Subproject2/SOVA/wwwroot/js/components/search-results/search-results.html
  Subproject2/SOVA/wwwroot/js/components/tag-filter/tag-filter.html
  Subproject2/SOVA/wwwroot/js/components/user-annotations/user-annotations.html
  Subproject2/SOVA/wwwroot/js/components/user-annotations/user-annotations.js
  Subproject2/SOVA/wwwroot/js/components/user-profile/user-profile.html
  Subproject2/SOVA/wwwroot/js/services/dataService.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#208 Linked posts in view
  Subproject2/SOVA/wwwroot/js/components/linked-posts/linked-posts.html
  Subproject2/SOVA/wwwroot/js/components/linked-posts/linked-posts.js
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.html
  Subproject2/SOVA/wwwroot/js/components/user-search-history/user-search-history.js
  Subproject2/SOVA/wwwroot/js/main.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#209 History sort by latest, by data with responsiveness
  Subproject2/Data Layer Abstractions/IUserHistoryRepository.cs
  Subproject2/Data Layer/UserHistoryRepository.cs
  Subproject2/SOVA/Controllers/HistoriesController.cs
  Subproject2/SOVA/wwwroot/assets/css/general.css
  Subproject2/SOVA/wwwroot/js/components/user-search-history/user-search-history.html
  Subproject2/SOVA/wwwroot/js/components/user-search-history/user-search-history.js
  Subproject2/SOVA/wwwroot/js/main.js
  Subproject2/SOVA/wwwroot/js/services/store.js
Labels: ready for review

#210 Updated README and cleaned up code
  README.md
  Subproject2/README.md
  Subproject2/Resources/Subproject3_Requiments.pdf
  Subproject2/SOVA/Controllers/AnnotationsController.cs
  Subproject2/SOVA/Controllers/HistoriesController.cs
  Subproject2/SOVA/Controllers/MarkingsController.cs
  Subproject2/SOVA/Controllers/QuestionsController.cs
  Subproject2/SOVA/Controllers/UsersController.cs
  Subproject2/SOVA/wwwroot/js/components/nav-bar/nav-bar.html
  Subproject2/Tests/DataServiceTests.cs
Labels: ready for review

#211 Bringing README up to date
  README.md
  Subproject2/README.md
  Subproject2/SOVA/Startup.cs
  Subproject2/SOVA/wwwroot/js/components/question-with-answers/question-with-answers.js
Labels: documentation, ready for review

#214 Preparing for release v3
  Subproject2/SOVA/Startup.cs
  Subproject2/Tests/DataServiceTests.cs
Labels: ready for review

#215 Rolled back connection strings
  Subproject2/SOVA/Startup.cs
  Subproject2/Tests/DataServiceTests.cs
Labels: ready for review
